-- Deprecated: use delete-module-content-data.sql instead.
-- The old single-table names (Comments, Messages, WebhookLogs) no longer exist.
--
-- Run:
--   psql "$DATABASE_URL" -f scripts/delete-module-content-data.sql
