$out = "C:\Users\win11\Desktop\Project\Social Media Project\backend\SocialMedia.Infrastructure\Persistence\Configurations\ModuleEntityConfigurations.cs"
$modules = @(
  @{ Prefix = "Integration"; Ns = "SocialMedia.Domain.Modules.Integrations.Entities"; TablePrefix = "Integration" },
  @{ Prefix = "AppConnection"; Ns = "SocialMedia.Domain.Modules.AppConnections.Entities"; TablePrefix = "AppConnection" },
  @{ Prefix = "DeveloperApp"; Ns = "SocialMedia.Domain.Modules.DeveloperApps.Entities"; TablePrefix = "DeveloperApp" }
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("using Microsoft.EntityFrameworkCore;")
[void]$sb.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;")
[void]$sb.AppendLine("using SocialMedia.Domain.Entities;")
foreach ($m in $modules) {
  [void]$sb.AppendLine("using $($m.Ns);")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace SocialMedia.Infrastructure.Persistence.Configurations;")
[void]$sb.AppendLine("")

foreach ($m in $modules) {
  $p = $m.Prefix
  $t = $m.TablePrefix
  $ns = $m.Ns

  [void]$sb.AppendLine("public class ${p}PlatformConfiguration : IEntityTypeConfiguration<${p}Platform>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}Platform> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}Platforms"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.Name).IsRequired().HasMaxLength(100);")
  [void]$sb.AppendLine("        builder.Property(x => x.Code).IsRequired().HasMaxLength(50);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.Code).IsUnique();")
  [void]$sb.AppendLine("        builder.Property(x => x.Icon).HasMaxLength(500);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}SocialAccountConfiguration : IEntityTypeConfiguration<${p}SocialAccount>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}SocialAccount> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}SocialAccounts"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.ExternalAccountId).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.DisplayName).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.Username).HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.Email).HasMaxLength(256);")
  [void]$sb.AppendLine("        builder.HasIndex(x => new { x.UserId, x.PlatformId }).IsUnique();")
  [void]$sb.AppendLine("        builder.HasOne(x => x.User).WithMany().HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Platform).WithMany(x => x.SocialAccounts).HasForeignKey(x => x.PlatformId).OnDelete(DeleteBehavior.Restrict);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Auth).WithOne(x => x.SocialAccount).HasForeignKey<${p}SocialAuth>(x => x.SocialAccountId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}SocialAuthConfiguration : IEntityTypeConfiguration<${p}SocialAuth>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}SocialAuth> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}SocialAuths"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.AccessToken).IsRequired();")
  [void]$sb.AppendLine("        builder.Property(x => x.Scopes).HasMaxLength(1000);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.SocialAccountId).IsUnique();")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}SocialProfileConfiguration : IEntityTypeConfiguration<${p}SocialProfile>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}SocialProfile> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}SocialProfiles"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.ExternalProfileId).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.Name).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.ExternalProfileId);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.SocialAccount).WithMany(x => x.Profiles).HasForeignKey(x => x.SocialAccountId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}PostConfiguration : IEntityTypeConfiguration<${p}Post>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}Post> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}Posts"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.ExternalPostId).HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.Text).HasMaxLength(5000);")
  [void]$sb.AppendLine("        builder.Property(x => x.Caption).HasMaxLength(5000);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.SocialProfile).WithMany(x => x.Posts).HasForeignKey(x => x.SocialProfileId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Platform).WithMany().HasForeignKey(x => x.PlatformId).OnDelete(DeleteBehavior.Restrict);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}MediaConfiguration : IEntityTypeConfiguration<${p}Media>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}Media> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}Media"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.Url).IsRequired().HasMaxLength(2000);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Post).WithMany(x => x.MediaItems).HasForeignKey(x => x.PostId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}CommentConfiguration : IEntityTypeConfiguration<${p}Comment>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}Comment> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}Comments"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.ExternalCommentId).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.AuthorName).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.Message).IsRequired().HasMaxLength(5000);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.ExternalCommentId).IsUnique();")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Post).WithMany(x => x.Comments).HasForeignKey(x => x.PostId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.ParentComment).WithMany(x => x.Replies).HasForeignKey(x => x.ParentCommentId).OnDelete(DeleteBehavior.Restrict);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}ConversationConfiguration : IEntityTypeConfiguration<${p}Conversation>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}Conversation> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}Conversations"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.ExternalConversationId).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.HasIndex(x => new { x.SocialProfileId, x.ExternalConversationId }).IsUnique();")
  [void]$sb.AppendLine("        builder.HasOne(x => x.SocialProfile).WithMany(x => x.Conversations).HasForeignKey(x => x.SocialProfileId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}MessageConfiguration : IEntityTypeConfiguration<${p}Message>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}Message> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}Messages"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.ExternalMessageId).IsRequired().HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.Property(x => x.Body).HasMaxLength(5000);")
  [void]$sb.AppendLine("        builder.Property(x => x.ReplyToExternalId).HasMaxLength(200);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.ExternalMessageId).IsUnique();")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Conversation).WithMany(x => x.Messages).HasForeignKey(x => x.ConversationId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}MessageAttachmentConfiguration : IEntityTypeConfiguration<${p}MessageAttachment>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}MessageAttachment> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}MessageAttachments"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.Url).IsRequired().HasMaxLength(2000);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Message).WithMany(x => x.Attachments).HasForeignKey(x => x.MessageId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}WebhookEventConfiguration : IEntityTypeConfiguration<${p}WebhookEvent>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}WebhookEvent> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}WebhookEvents"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.EventType).IsRequired().HasMaxLength(100);")
  [void]$sb.AppendLine("        builder.Property(x => x.PayloadJson).IsRequired();")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Platform).WithMany().HasForeignKey(x => x.PlatformId).OnDelete(DeleteBehavior.SetNull);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.Status);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}WebhookLogConfiguration : IEntityTypeConfiguration<${p}WebhookLog>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}WebhookLog> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}WebhookLogs"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.Property(x => x.PlatformCode).IsRequired().HasMaxLength(50);")
  [void]$sb.AppendLine("        builder.Property(x => x.PayloadJson).IsRequired();")
  [void]$sb.AppendLine("        builder.HasOne(x => x.Platform).WithMany().HasForeignKey(x => x.PlatformId).OnDelete(DeleteBehavior.SetNull);")
  [void]$sb.AppendLine("        builder.HasIndex(x => x.ReceivedAt);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")

  [void]$sb.AppendLine("public class ${p}SyncJobConfiguration : IEntityTypeConfiguration<${p}SyncJob>")
  [void]$sb.AppendLine("{")
  [void]$sb.AppendLine("    public void Configure(EntityTypeBuilder<${p}SyncJob> builder)")
  [void]$sb.AppendLine("    {")
  [void]$sb.AppendLine("        builder.ToTable(""${t}SyncJobs"");")
  [void]$sb.AppendLine("        builder.HasKey(x => x.Id);")
  [void]$sb.AppendLine("        builder.HasOne(x => x.SocialAccount).WithMany(x => x.SyncJobs).HasForeignKey(x => x.SocialAccountId).OnDelete(DeleteBehavior.Cascade);")
  [void]$sb.AppendLine("    }")
  [void]$sb.AppendLine("}")
  [void]$sb.AppendLine("")
}

[System.IO.File]::WriteAllText($out, $sb.ToString())
Write-Host "Wrote $out"
